package main

type Finger int

type Key struct {
	Label     string
	Width     int
	Finger    Finger
	Gap       bool
	Rightless bool
	Leftless  bool
	DivLabel  string
	EvCode    uint16
}

const (
	FingerPinky Finger = iota
	FingerRing
	FingerMiddle
	FingerIndex
	FingerThumb
)

var keyboardSizes = map[int][][]Key{
	60:  size60,
	65:  size65,
	75:  size75,
	80:  size80,
	96:  size96,
	100: size100,
}

var size60 = [][]Key{
	// Row 0: Number row
	{
		{Label: "⎋", Width: 3, Finger: FingerPinky, EvCode: 1},
		{Label: "1", Width: 3, Finger: FingerPinky, EvCode: 2},
		{Label: "2", Width: 3, Finger: FingerRing, EvCode: 3},
		{Label: "3", Width: 3, Finger: FingerMiddle, EvCode: 4},
		{Label: "4", Width: 3, Finger: FingerIndex, EvCode: 5},
		{Label: "5", Width: 3, Finger: FingerIndex, EvCode: 6},
		{Label: "6", Width: 3, Finger: FingerIndex, EvCode: 7},
		{Label: "7", Width: 3, Finger: FingerIndex, EvCode: 8},
		{Label: "8", Width: 3, Finger: FingerMiddle, EvCode: 9},
		{Label: "9", Width: 3, Finger: FingerRing, EvCode: 10},
		{Label: "0", Width: 3, Finger: FingerPinky, EvCode: 11},
		{Label: "-", Width: 3, Finger: FingerPinky, EvCode: 12},
		{Label: "=", Width: 3, Finger: FingerPinky, EvCode: 13},
		{Label: "<--", Width: 8, Finger: FingerPinky, EvCode: 14},
	},
	// Row 1: Top alpha
	{
		{Label: "Tab⇄", Width: 6, Finger: FingerPinky, EvCode: 15},
		{Label: "Q", Width: 3, Finger: FingerPinky, EvCode: 16},
		{Label: "W", Width: 3, Finger: FingerRing, EvCode: 17},
		{Label: "E", Width: 3, Finger: FingerMiddle, EvCode: 18},
		{Label: "R", Width: 3, Finger: FingerIndex, EvCode: 19},
		{Label: "T", Width: 3, Finger: FingerIndex, EvCode: 20},
		{Label: "Y", Width: 3, Finger: FingerIndex, EvCode: 21},
		{Label: "U", Width: 3, Finger: FingerIndex, EvCode: 22},
		{Label: "I", Width: 3, Finger: FingerMiddle, EvCode: 23},
		{Label: "O", Width: 3, Finger: FingerRing, EvCode: 24},
		{Label: "P", Width: 3, Finger: FingerPinky, EvCode: 25},
		{Label: "[", Width: 3, Finger: FingerPinky, EvCode: 26},
		{Label: "]", Width: 3, Finger: FingerPinky, EvCode: 27},
		{Label: "\\", Width: 5, Finger: FingerPinky, EvCode: 43},
	},
	// Row 2: Home row
	{
		{Label: "Caps", Width: 6, Finger: FingerPinky, EvCode: 58},
		{Label: "A", Width: 3, Finger: FingerPinky, EvCode: 30},
		{Label: "S", Width: 3, Finger: FingerRing, EvCode: 31},
		{Label: "D", Width: 3, Finger: FingerMiddle, EvCode: 32},
		{Label: "F", Width: 3, Finger: FingerIndex, EvCode: 33},
		{Label: "G", Width: 3, Finger: FingerIndex, EvCode: 34},
		{Label: "H", Width: 3, Finger: FingerIndex, EvCode: 35},
		{Label: "J", Width: 3, Finger: FingerIndex, EvCode: 36},
		{Label: "K", Width: 3, Finger: FingerMiddle, EvCode: 37},
		{Label: "L", Width: 3, Finger: FingerRing, EvCode: 38},
		{Label: ";", Width: 3, Finger: FingerPinky, EvCode: 39},
		{Label: "'", Width: 3, Finger: FingerPinky, EvCode: 40},
		{Label: "Enter↵", Width: 9, Finger: FingerPinky, EvCode: 28},
	},
	// Row 3: Bottom alpha
	{
		{Label: "Shift", Width: 10, Finger: FingerPinky, EvCode: 42},
		{Label: "Z", Width: 3, Finger: FingerPinky, EvCode: 44},
		{Label: "X", Width: 3, Finger: FingerRing, EvCode: 45},
		{Label: "C", Width: 3, Finger: FingerMiddle, EvCode: 46},
		{Label: "V", Width: 3, Finger: FingerIndex, EvCode: 47},
		{Label: "B", Width: 3, Finger: FingerIndex, EvCode: 48},
		{Label: "N", Width: 3, Finger: FingerIndex, EvCode: 49},
		{Label: "M", Width: 3, Finger: FingerIndex, EvCode: 50},
		{Label: ",", Width: 3, Finger: FingerMiddle, EvCode: 51},
		{Label: ".", Width: 3, Finger: FingerRing, EvCode: 52},
		{Label: "/", Width: 3, Finger: FingerPinky, EvCode: 53},
		{Label: "Shift", Width: 9, Finger: FingerPinky, EvCode: 54},
	},
	// Row 4: Modifiers
	{
		{Label: "Ctrl", Width: 6, Finger: FingerPinky, EvCode: 29},
		{Label: "⌘", Width: 3, Finger: FingerRing, EvCode: 125},
		{Label: "Alt", Width: 5, Finger: FingerThumb, EvCode: 56},
		{Label: "Space", Width: 22, Finger: FingerThumb, EvCode: 57},
		{Label: "Alt", Width: 5, Finger: FingerThumb, EvCode: 100},
		{Label: "⌘", Width: 3, Finger: FingerRing, EvCode: 126},
		{Label: "Fn", Width: 3, Finger: FingerRing, EvCode: 127},
		{Label: "Ctrl", Width: 6, Finger: FingerPinky, EvCode: 97},
	},
}

var size65 = [][]Key{
	// Row 0: Number row + Del
	{
		{Label: "⎋", Width: 3, Finger: FingerPinky, EvCode: 1},
		{Label: "1", Width: 3, Finger: FingerPinky, EvCode: 2},
		{Label: "2", Width: 3, Finger: FingerRing, EvCode: 3},
		{Label: "3", Width: 3, Finger: FingerMiddle, EvCode: 4},
		{Label: "4", Width: 3, Finger: FingerIndex, EvCode: 5},
		{Label: "5", Width: 3, Finger: FingerIndex, EvCode: 6},
		{Label: "6", Width: 3, Finger: FingerIndex, EvCode: 7},
		{Label: "7", Width: 3, Finger: FingerIndex, EvCode: 8},
		{Label: "8", Width: 3, Finger: FingerMiddle, EvCode: 9},
		{Label: "9", Width: 3, Finger: FingerRing, EvCode: 10},
		{Label: "0", Width: 3, Finger: FingerPinky, EvCode: 11},
		{Label: "-", Width: 3, Finger: FingerPinky, EvCode: 12},
		{Label: "=", Width: 3, Finger: FingerPinky, EvCode: 13},
		{Label: "<--", Width: 8, Finger: FingerPinky, EvCode: 14},
		{Label: "☼", Width: 3, Finger: FingerPinky, EvCode: 111},
	},
	// Row 1: Top alpha + PgUp
	{
		{Label: "Tab⇄", Width: 6, Finger: FingerPinky, EvCode: 15},
		{Label: "Q", Width: 3, Finger: FingerPinky, EvCode: 16},
		{Label: "W", Width: 3, Finger: FingerRing, EvCode: 17},
		{Label: "E", Width: 3, Finger: FingerMiddle, EvCode: 18},
		{Label: "R", Width: 3, Finger: FingerIndex, EvCode: 19},
		{Label: "T", Width: 3, Finger: FingerIndex, EvCode: 20},
		{Label: "Y", Width: 3, Finger: FingerIndex, EvCode: 21},
		{Label: "U", Width: 3, Finger: FingerIndex, EvCode: 22},
		{Label: "I", Width: 3, Finger: FingerMiddle, EvCode: 23},
		{Label: "O", Width: 3, Finger: FingerRing, EvCode: 24},
		{Label: "P", Width: 3, Finger: FingerPinky, EvCode: 25},
		{Label: "[", Width: 3, Finger: FingerPinky, EvCode: 26},
		{Label: "]", Width: 3, Finger: FingerPinky, EvCode: 27},
		{Label: "\\", Width: 5, Finger: FingerPinky, EvCode: 43},
		{Label: "⌂", Width: 3, Finger: FingerPinky, EvCode: 102},
	},
	// Row 2: Home row + PgDn
	{
		{Label: "Caps", Width: 6, Finger: FingerPinky, EvCode: 58},
		{Label: "A", Width: 3, Finger: FingerPinky, EvCode: 30},
		{Label: "S", Width: 3, Finger: FingerRing, EvCode: 31},
		{Label: "D", Width: 3, Finger: FingerMiddle, EvCode: 32},
		{Label: "F", Width: 3, Finger: FingerIndex, EvCode: 33},
		{Label: "G", Width: 3, Finger: FingerIndex, EvCode: 34},
		{Label: "H", Width: 3, Finger: FingerIndex, EvCode: 35},
		{Label: "J", Width: 3, Finger: FingerIndex, EvCode: 36},
		{Label: "K", Width: 3, Finger: FingerMiddle, EvCode: 37},
		{Label: "L", Width: 3, Finger: FingerRing, EvCode: 38},
		{Label: ";", Width: 3, Finger: FingerPinky, EvCode: 39},
		{Label: "'", Width: 3, Finger: FingerPinky, EvCode: 40},
		{Label: "Enter↵", Width: 9, Finger: FingerPinky, EvCode: 28},
		{Label: "⇡", Width: 3, Finger: FingerPinky, EvCode: 104},
	},
	// Row 3: Bottom alpha + Home + End
	{
		{Label: "Shift", Width: 8, Finger: FingerPinky, EvCode: 42},
		{Label: "Z", Width: 3, Finger: FingerPinky, EvCode: 44},
		{Label: "X", Width: 3, Finger: FingerRing, EvCode: 45},
		{Label: "C", Width: 3, Finger: FingerMiddle, EvCode: 46},
		{Label: "V", Width: 3, Finger: FingerIndex, EvCode: 47},
		{Label: "B", Width: 3, Finger: FingerIndex, EvCode: 48},
		{Label: "N", Width: 3, Finger: FingerIndex, EvCode: 49},
		{Label: "M", Width: 3, Finger: FingerIndex, EvCode: 50},
		{Label: ",", Width: 3, Finger: FingerMiddle, EvCode: 51},
		{Label: ".", Width: 3, Finger: FingerRing, EvCode: 52},
		{Label: "/", Width: 3, Finger: FingerPinky, EvCode: 53},
		{Label: "Shift", Width: 7, Finger: FingerPinky, EvCode: 54},
		{Label: "↑", Width: 3, Finger: FingerPinky, EvCode: 103},
		{Label: "⇣", Width: 3, Finger: FingerPinky, EvCode: 109},
	},
	// Row 4: Modifiers + arrows
	{
		{Label: "Ctrl", Width: 6, Finger: FingerPinky, EvCode: 29},
		{Label: "⌘", Width: 3, Finger: FingerRing, EvCode: 125},
		{Label: "Alt", Width: 3, Finger: FingerThumb, EvCode: 56},
		{Label: "Space", Width: 22, Finger: FingerThumb, EvCode: 57},
		{Label: "Alt", Width: 3, Finger: FingerThumb, EvCode: 100},
		{Label: "Fn", Width: 3, Finger: FingerRing, EvCode: 127},
		{Label: "Ctrl", Width: 6, Finger: FingerPinky, EvCode: 97},
		{Label: "←", Width: 3, Finger: FingerPinky, EvCode: 105},
		{Label: "↓", Width: 3, Finger: FingerPinky, EvCode: 108},
		{Label: "→", Width: 3, Finger: FingerPinky, EvCode: 106},
	},
}

var size75 = [][]Key{
	// Row 0: Esc + F1-F12 + PrSc + Del + Pse
	{
		{Label: "⎋", Width: 3, Finger: FingerPinky, EvCode: 1},
		{Label: "F1", Width: 3, Finger: FingerPinky, EvCode: 59},
		{Label: "F2", Width: 3, Finger: FingerRing, EvCode: 60},
		{Label: "F3", Width: 3, Finger: FingerMiddle, EvCode: 61},
		{Label: "F4", Width: 3, Finger: FingerIndex, EvCode: 62},
		{Label: "F5", Width: 3, Finger: FingerIndex, EvCode: 63},
		{Label: "F6", Width: 3, Finger: FingerIndex, EvCode: 64},
		{Label: "F7", Width: 3, Finger: FingerIndex, EvCode: 65},
		{Label: "F8", Width: 3, Finger: FingerMiddle, EvCode: 66},
		{Label: "F9", Width: 3, Finger: FingerRing, EvCode: 67},
		{Label: "F10", Width: 3, Finger: FingerPinky, EvCode: 68},
		{Label: "F11", Width: 3, Finger: FingerPinky, EvCode: 87},
		{Label: "F12", Width: 3, Finger: FingerPinky, EvCode: 88},
		{Label: "⎚", Width: 3, Finger: FingerPinky, EvCode: 99},
		{Label: "Del", Width: 4, Finger: FingerPinky, EvCode: 111},
		{Label: "☼", Width: 3, Finger: FingerPinky, EvCode: 119},
	},
	// Row 1: Number row
	{
		{Label: "`", Width: 3, Finger: FingerPinky, EvCode: 41},
		{Label: "1", Width: 3, Finger: FingerPinky, EvCode: 2},
		{Label: "2", Width: 3, Finger: FingerRing, EvCode: 3},
		{Label: "3", Width: 3, Finger: FingerMiddle, EvCode: 4},
		{Label: "4", Width: 3, Finger: FingerIndex, EvCode: 5},
		{Label: "5", Width: 3, Finger: FingerIndex, EvCode: 6},
		{Label: "6", Width: 3, Finger: FingerIndex, EvCode: 7},
		{Label: "7", Width: 3, Finger: FingerIndex, EvCode: 8},
		{Label: "8", Width: 3, Finger: FingerMiddle, EvCode: 9},
		{Label: "9", Width: 3, Finger: FingerRing, EvCode: 10},
		{Label: "0", Width: 3, Finger: FingerPinky, EvCode: 11},
		{Label: "-", Width: 3, Finger: FingerPinky, EvCode: 12},
		{Label: "=", Width: 3, Finger: FingerPinky, EvCode: 13},
		{Label: "<--", Width: 8, Finger: FingerPinky, EvCode: 14},
		{Label: "⇡", Width: 3, Finger: FingerPinky, EvCode: 104},
	},
	// Row 2: Top alpha
	{
		{Label: "Tab⇄", Width: 6, Finger: FingerPinky, EvCode: 15},
		{Label: "Q", Width: 3, Finger: FingerPinky, EvCode: 16},
		{Label: "W", Width: 3, Finger: FingerRing, EvCode: 17},
		{Label: "E", Width: 3, Finger: FingerMiddle, EvCode: 18},
		{Label: "R", Width: 3, Finger: FingerIndex, EvCode: 19},
		{Label: "T", Width: 3, Finger: FingerIndex, EvCode: 20},
		{Label: "Y", Width: 3, Finger: FingerIndex, EvCode: 21},
		{Label: "U", Width: 3, Finger: FingerIndex, EvCode: 22},
		{Label: "I", Width: 3, Finger: FingerMiddle, EvCode: 23},
		{Label: "O", Width: 3, Finger: FingerRing, EvCode: 24},
		{Label: "P", Width: 3, Finger: FingerPinky, EvCode: 25},
		{Label: "[", Width: 3, Finger: FingerPinky, EvCode: 26},
		{Label: "]", Width: 3, Finger: FingerPinky, EvCode: 27},
		{Label: "\\", Width: 5, Finger: FingerPinky, EvCode: 43},
		{Label: "⇣", Width: 3, Finger: FingerPinky, EvCode: 109},
	},
	// Row 3: Home row
	{
		{Label: "Caps", Width: 6, Finger: FingerPinky, EvCode: 58},
		{Label: "A", Width: 3, Finger: FingerPinky, EvCode: 30},
		{Label: "S", Width: 3, Finger: FingerRing, EvCode: 31},
		{Label: "D", Width: 3, Finger: FingerMiddle, EvCode: 32},
		{Label: "F", Width: 3, Finger: FingerIndex, EvCode: 33},
		{Label: "G", Width: 3, Finger: FingerIndex, EvCode: 34},
		{Label: "H", Width: 3, Finger: FingerIndex, EvCode: 35},
		{Label: "J", Width: 3, Finger: FingerIndex, EvCode: 36},
		{Label: "K", Width: 3, Finger: FingerMiddle, EvCode: 37},
		{Label: "L", Width: 3, Finger: FingerRing, EvCode: 38},
		{Label: ";", Width: 3, Finger: FingerPinky, EvCode: 39},
		{Label: "'", Width: 3, Finger: FingerPinky, EvCode: 40},
		{Label: "Enter↵", Width: 9, Finger: FingerPinky, EvCode: 28},
		{Label: "⌂", Width: 3, Finger: FingerPinky, EvCode: 102},
	},
	// Row 4: Bottom alpha + up arrow
	{
		{Label: "Shift", Width: 8, Finger: FingerPinky, EvCode: 42},
		{Label: "Z", Width: 3, Finger: FingerPinky, EvCode: 44},
		{Label: "X", Width: 3, Finger: FingerRing, EvCode: 45},
		{Label: "C", Width: 3, Finger: FingerMiddle, EvCode: 46},
		{Label: "V", Width: 3, Finger: FingerIndex, EvCode: 47},
		{Label: "B", Width: 3, Finger: FingerIndex, EvCode: 48},
		{Label: "N", Width: 3, Finger: FingerIndex, EvCode: 49},
		{Label: "M", Width: 3, Finger: FingerIndex, EvCode: 50},
		{Label: ",", Width: 3, Finger: FingerMiddle, EvCode: 51},
		{Label: ".", Width: 3, Finger: FingerRing, EvCode: 52},
		{Label: "/", Width: 3, Finger: FingerPinky, EvCode: 53},
		{Label: "Shift", Width: 7, Finger: FingerPinky, EvCode: 54},
		{Label: "↑", Width: 3, Finger: FingerPinky, EvCode: 103},
		{Label: "⌿", Width: 3, Finger: FingerPinky, EvCode: 107},
	},
	// Row 5: Modifiers + arrows
	{
		{Label: "Ctrl", Width: 6, Finger: FingerPinky, EvCode: 29},
		{Label: "⌘", Width: 3, Finger: FingerRing, EvCode: 125},
		{Label: "Alt", Width: 3, Finger: FingerThumb, EvCode: 56},
		{Label: "Space", Width: 22, Finger: FingerThumb, EvCode: 57},
		{Label: "Alt", Width: 3, Finger: FingerThumb, EvCode: 100},
		{Label: "Fn", Width: 3, Finger: FingerRing, EvCode: 127},
		{Label: "Ctrl", Width: 6, Finger: FingerPinky, EvCode: 97},
		{Label: "←", Width: 3, Finger: FingerPinky, EvCode: 105},
		{Label: "↓", Width: 3, Finger: FingerPinky, EvCode: 108},
		{Label: "→", Width: 3, Finger: FingerPinky, EvCode: 106},
	},
}

var size80 = [][]Key{
	// Row 0: Esc + F1-F12 + PrSc + ScLk + Pse
	{
		{Label: "⎋", Width: 3, Finger: FingerPinky, EvCode: 1},
		{Label: "   ", Width: 3, Finger: FingerPinky, EvCode: 0},
		{Label: "F1", Width: 3, Finger: FingerPinky, EvCode: 59},
		{Label: "F2", Width: 3, Finger: FingerRing, EvCode: 60},
		{Label: "F3", Width: 3, Finger: FingerMiddle, EvCode: 61},
		{Label: "F4", Width: 3, Finger: FingerIndex, EvCode: 62},
		{Label: "  ", Width: 2, Finger: FingerIndex, EvCode: 0},
		{Label: "F5", Width: 3, Finger: FingerIndex, EvCode: 63},
		{Label: "F6", Width: 3, Finger: FingerIndex, EvCode: 64},
		{Label: "F7", Width: 3, Finger: FingerIndex, EvCode: 65},
		{Label: "F8", Width: 3, Finger: FingerMiddle, EvCode: 66},
		{Label: "  ", Width: 2, Finger: FingerIndex, EvCode: 0},
		{Label: "F9", Width: 3, Finger: FingerRing, EvCode: 67},
		{Label: "F10", Width: 3, Finger: FingerPinky, EvCode: 68},
		{Label: "F11", Width: 3, Finger: FingerPinky, EvCode: 87},
		{Label: "F12", Width: 3, Finger: FingerPinky, EvCode: 88},
		{Label: "  ", Width: 2, Finger: FingerIndex, Gap: true, EvCode: 0},
		{Label: "⎚", Width: 3, Finger: FingerPinky, EvCode: 99},
		{Label: "⚲", Width: 3, Finger: FingerPinky, EvCode: 70},
		{Label: "☼", Width: 3, Finger: FingerPinky, EvCode: 119},
	},
	// Row 1: Number row + Ins + Hme + PgUp
	{
		{Label: "`", Width: 3, Finger: FingerPinky, EvCode: 41},
		{Label: "1", Width: 3, Finger: FingerPinky, EvCode: 2},
		{Label: "2", Width: 3, Finger: FingerRing, EvCode: 3},
		{Label: "3", Width: 3, Finger: FingerMiddle, EvCode: 4},
		{Label: "4", Width: 3, Finger: FingerIndex, EvCode: 5},
		{Label: "5", Width: 3, Finger: FingerIndex, EvCode: 6},
		{Label: "6", Width: 3, Finger: FingerIndex, EvCode: 7},
		{Label: "7", Width: 3, Finger: FingerIndex, EvCode: 8},
		{Label: "8", Width: 3, Finger: FingerMiddle, EvCode: 9},
		{Label: "9", Width: 3, Finger: FingerRing, EvCode: 10},
		{Label: "0", Width: 3, Finger: FingerPinky, EvCode: 11},
		{Label: "-", Width: 3, Finger: FingerPinky, EvCode: 12},
		{Label: "=", Width: 3, Finger: FingerPinky, EvCode: 13},
		{Label: "<--", Width: 9, Finger: FingerPinky, EvCode: 14},
		{Label: "  ", Width: 2, Finger: FingerPinky, Gap: true, EvCode: 0},
		{Label: "Ins", Width: 3, Finger: FingerPinky, EvCode: 110},
		{Label: "⌂", Width: 3, Finger: FingerPinky, EvCode: 102},
		{Label: "⇡", Width: 3, Finger: FingerPinky, EvCode: 104},
	},
	// Row 2: Top alpha + Del + End + PgDn
	{
		{Label: "Tab⇄", Width: 7, Finger: FingerPinky, EvCode: 15},
		{Label: "Q", Width: 3, Finger: FingerPinky, EvCode: 16},
		{Label: "W", Width: 3, Finger: FingerRing, EvCode: 17},
		{Label: "E", Width: 3, Finger: FingerMiddle, EvCode: 18},
		{Label: "R", Width: 3, Finger: FingerIndex, EvCode: 19},
		{Label: "T", Width: 3, Finger: FingerIndex, EvCode: 20},
		{Label: "Y", Width: 3, Finger: FingerIndex, EvCode: 21},
		{Label: "U", Width: 3, Finger: FingerIndex, EvCode: 22},
		{Label: "I", Width: 3, Finger: FingerMiddle, EvCode: 23},
		{Label: "O", Width: 3, Finger: FingerRing, EvCode: 24},
		{Label: "P", Width: 3, Finger: FingerPinky, EvCode: 25},
		{Label: "[", Width: 3, Finger: FingerPinky, EvCode: 26},
		{Label: "]", Width: 3, Finger: FingerPinky, EvCode: 27},
		{Label: "\\", Width: 5, Finger: FingerPinky, EvCode: 43},
		{Label: "  ", Width: 2, Finger: FingerPinky, Gap: true, EvCode: 0},
		{Label: "Del", Width: 3, Finger: FingerPinky, EvCode: 111},
		{Label: "⌿", Width: 3, Finger: FingerPinky, EvCode: 107},
		{Label: "⇣", Width: 3, Finger: FingerPinky, EvCode: 109},
	},
	// Row 3: Home row
	{
		{Label: "Caps", Width: 6, Finger: FingerPinky, EvCode: 58},
		{Label: "A", Width: 3, Finger: FingerPinky, EvCode: 30},
		{Label: "S", Width: 3, Finger: FingerRing, EvCode: 31},
		{Label: "D", Width: 3, Finger: FingerMiddle, EvCode: 32},
		{Label: "F", Width: 3, Finger: FingerIndex, EvCode: 33},
		{Label: "G", Width: 3, Finger: FingerIndex, EvCode: 34},
		{Label: "H", Width: 3, Finger: FingerIndex, EvCode: 35},
		{Label: "J", Width: 3, Finger: FingerIndex, EvCode: 36},
		{Label: "K", Width: 3, Finger: FingerMiddle, EvCode: 37},
		{Label: "L", Width: 3, Finger: FingerRing, EvCode: 38},
		{Label: ";", Width: 3, Finger: FingerPinky, EvCode: 39},
		{Label: "'", Width: 3, Finger: FingerPinky, EvCode: 40},
		{Label: "Enter↵", Width: 10, Finger: FingerPinky, EvCode: 28},
		{Label: "      ", Width: 6, Finger: FingerPinky, Gap: true, Rightless: true, Leftless: false, EvCode: 0},
		{Label: "   ", Width: 3, Finger: FingerPinky, Gap: false, Rightless: true, Leftless: true, EvCode: 0},
		{Label: "   ", Width: 3, Finger: FingerPinky, Gap: true, Rightless: false, Leftless: false, EvCode: 0},
	},
	// Row 4: Bottom alpha + ↑
	{
		{Label: "Shift", Width: 11, Finger: FingerPinky, EvCode: 42},
		{Label: "Z", Width: 3, Finger: FingerPinky, EvCode: 44},
		{Label: "X", Width: 3, Finger: FingerRing, EvCode: 45},
		{Label: "C", Width: 3, Finger: FingerMiddle, EvCode: 46},
		{Label: "V", Width: 3, Finger: FingerIndex, EvCode: 47},
		{Label: "B", Width: 3, Finger: FingerIndex, EvCode: 48},
		{Label: "N", Width: 3, Finger: FingerIndex, EvCode: 49},
		{Label: "M", Width: 3, Finger: FingerIndex, EvCode: 50},
		{Label: ",", Width: 3, Finger: FingerMiddle, EvCode: 51},
		{Label: ".", Width: 3, Finger: FingerRing, EvCode: 52},
		{Label: "/", Width: 3, Finger: FingerPinky, EvCode: 53},
		{Label: "Shift", Width: 9, Finger: FingerPinky, EvCode: 54},
		{Label: "  ", Width: 2, Finger: FingerPinky, Gap: true, Rightless: true, Leftless: false, EvCode: 0},
		{Label: "   ", Width: 3, Finger: FingerPinky, EvCode: 0},
		{Label: "↑", Width: 3, Finger: FingerPinky, EvCode: 103},
		{Label: "   ", Width: 3, Finger: FingerPinky, EvCode: 0},
	},
	// Row 5: Modifiers + arrows
	{
		{Label: "Ctrl", Width: 6, Finger: FingerPinky, EvCode: 29},
		{Label: "⌘", Width: 3, Finger: FingerRing, EvCode: 125},
		{Label: "Alt", Width: 5, Finger: FingerThumb, EvCode: 56},
		{Label: "Space", Width: 23, Finger: FingerThumb, EvCode: 57},
		{Label: "Alt", Width: 5, Finger: FingerThumb, EvCode: 100},
		{Label: "⌘", Width: 3, Finger: FingerRing, EvCode: 126},
		{Label: "Fn", Width: 3, Finger: FingerRing, EvCode: 127},
		{Label: "Ctrl", Width: 6, Finger: FingerPinky, EvCode: 97},
		{Label: "  ", Width: 2, Finger: FingerPinky, EvCode: 0},
		{Label: "←", Width: 3, Finger: FingerPinky, EvCode: 105},
		{Label: "↓", Width: 3, Finger: FingerPinky, EvCode: 108},
		{Label: "→", Width: 3, Finger: FingerPinky, EvCode: 106},
	},
}

var size96 = [][]Key{
	// Row 0: Esc + F1-F12 + Del + Home + End + PgUp + PgDn + Pse
	{
		{Label: "⎋", Width: 3, Finger: FingerPinky, EvCode: 1},
		{Label: "F1", Width: 3, Finger: FingerPinky, EvCode: 59},
		{Label: "F2", Width: 3, Finger: FingerRing, EvCode: 60},
		{Label: "F3", Width: 3, Finger: FingerMiddle, EvCode: 61},
		{Label: "F4", Width: 3, Finger: FingerIndex, EvCode: 62},
		{Label: "F5", Width: 3, Finger: FingerIndex, EvCode: 63},
		{Label: "F6", Width: 3, Finger: FingerIndex, EvCode: 64},
		{Label: "F7", Width: 3, Finger: FingerIndex, EvCode: 65},
		{Label: "F8", Width: 3, Finger: FingerMiddle, EvCode: 66},
		{Label: "F9", Width: 3, Finger: FingerRing, EvCode: 67},
		{Label: "F10", Width: 3, Finger: FingerPinky, EvCode: 68},
		{Label: "F11", Width: 3, Finger: FingerPinky, EvCode: 87},
		{Label: "F12", Width: 3, Finger: FingerPinky, EvCode: 88},
		{Label: "Del", Width: 3, Finger: FingerPinky, EvCode: 111},
		{Label: "⌂", Width: 3, Finger: FingerPinky, EvCode: 102},
		{Label: "⌿", Width: 3, Finger: FingerPinky, EvCode: 107},
		{Label: "⇡", Width: 3, Finger: FingerPinky, EvCode: 104},
		{Label: "⇣", Width: 3, Finger: FingerPinky, EvCode: 109},
		{Label: "☼", Width: 3, Finger: FingerPinky, EvCode: 119},
	},
	// Row 1: Number row + NmLk + / + * + -
	{
		{Label: "`", Width: 3, Finger: FingerPinky, EvCode: 41},
		{Label: "1", Width: 3, Finger: FingerPinky, EvCode: 2},
		{Label: "2", Width: 3, Finger: FingerRing, EvCode: 3},
		{Label: "3", Width: 3, Finger: FingerMiddle, EvCode: 4},
		{Label: "4", Width: 3, Finger: FingerIndex, EvCode: 5},
		{Label: "5", Width: 3, Finger: FingerIndex, EvCode: 6},
		{Label: "6", Width: 3, Finger: FingerIndex, EvCode: 7},
		{Label: "7", Width: 3, Finger: FingerIndex, EvCode: 8},
		{Label: "8", Width: 3, Finger: FingerMiddle, EvCode: 9},
		{Label: "9", Width: 3, Finger: FingerRing, EvCode: 10},
		{Label: "0", Width: 3, Finger: FingerPinky, EvCode: 11},
		{Label: "-", Width: 3, Finger: FingerPinky, EvCode: 12},
		{Label: "=", Width: 3, Finger: FingerPinky, EvCode: 13},
		{Label: "<--", Width: 7, Finger: FingerPinky, EvCode: 14},
		{Label: "Nlk", Width: 3, Finger: FingerPinky, EvCode: 69},
		{Label: "/", Width: 3, Finger: FingerPinky, EvCode: 98},
		{Label: "*", Width: 3, Finger: FingerPinky, EvCode: 55},
		{Label: "-", Width: 3, Finger: FingerPinky, EvCode: 74},
	},
	// Row 2: Top alpha + 7 + 8 + 9 + +
	{
		{Label: "Tab ⇄", Width: 7, Finger: FingerPinky, EvCode: 15},
		{Label: "Q", Width: 3, Finger: FingerPinky, EvCode: 16},
		{Label: "W", Width: 3, Finger: FingerRing, EvCode: 17},
		{Label: "E", Width: 3, Finger: FingerMiddle, EvCode: 18},
		{Label: "R", Width: 3, Finger: FingerIndex, EvCode: 19},
		{Label: "T", Width: 3, Finger: FingerIndex, EvCode: 20},
		{Label: "Y", Width: 3, Finger: FingerIndex, EvCode: 21},
		{Label: "U", Width: 3, Finger: FingerIndex, EvCode: 22},
		{Label: "I", Width: 3, Finger: FingerMiddle, EvCode: 23},
		{Label: "O", Width: 3, Finger: FingerRing, EvCode: 24},
		{Label: "P", Width: 3, Finger: FingerPinky, EvCode: 25},
		{Label: "[", Width: 3, Finger: FingerPinky, EvCode: 26},
		{Label: "]", Width: 3, Finger: FingerPinky, EvCode: 27},
		{Label: "\\", Width: 3, Finger: FingerPinky, EvCode: 43},
		{Label: "7", Width: 3, Finger: FingerPinky, EvCode: 71},
		{Label: "8", Width: 3, Finger: FingerPinky, EvCode: 72},
		{Label: "9", Width: 3, Finger: FingerPinky, EvCode: 73},
		{Label: "   ", Width: 3, Finger: FingerPinky, Gap: true, DivLabel: "+", EvCode: 78},
	},
	// Row 3: Home row + 4 + 5 + 6 (blank for +)
	{
		{Label: "Caps", Width: 6, Finger: FingerPinky, EvCode: 58},
		{Label: "A", Width: 3, Finger: FingerPinky, EvCode: 30},
		{Label: "S", Width: 3, Finger: FingerRing, EvCode: 31},
		{Label: "D", Width: 3, Finger: FingerMiddle, EvCode: 32},
		{Label: "F", Width: 3, Finger: FingerIndex, EvCode: 33},
		{Label: "G", Width: 3, Finger: FingerIndex, EvCode: 34},
		{Label: "H", Width: 3, Finger: FingerIndex, EvCode: 35},
		{Label: "J", Width: 3, Finger: FingerIndex, EvCode: 36},
		{Label: "K", Width: 3, Finger: FingerMiddle, EvCode: 37},
		{Label: "L", Width: 3, Finger: FingerRing, EvCode: 38},
		{Label: ";", Width: 3, Finger: FingerPinky, EvCode: 39},
		{Label: "'", Width: 3, Finger: FingerPinky, EvCode: 40},
		{Label: "Enter↵", Width: 8, Finger: FingerPinky, EvCode: 28},
		{Label: "4", Width: 3, Finger: FingerPinky, EvCode: 75},
		{Label: "5", Width: 3, Finger: FingerPinky, EvCode: 76},
		{Label: "6", Width: 3, Finger: FingerPinky, EvCode: 77},
		{Label: "   ", Width: 3, Finger: FingerPinky, EvCode: 0},
	},
	// Row 4: Bottom alpha + ↑ + 1 + 2 + 3 (blank for ↵)
	{
		{Label: "Shift", Width: 7, Finger: FingerPinky, EvCode: 42},
		{Label: "Z", Width: 3, Finger: FingerPinky, EvCode: 44},
		{Label: "X", Width: 3, Finger: FingerRing, EvCode: 45},
		{Label: "C", Width: 3, Finger: FingerMiddle, EvCode: 46},
		{Label: "V", Width: 3, Finger: FingerIndex, EvCode: 47},
		{Label: "B", Width: 3, Finger: FingerIndex, EvCode: 48},
		{Label: "N", Width: 3, Finger: FingerIndex, EvCode: 49},
		{Label: "M", Width: 3, Finger: FingerIndex, EvCode: 50},
		{Label: ",", Width: 3, Finger: FingerMiddle, EvCode: 51},
		{Label: ".", Width: 3, Finger: FingerRing, EvCode: 52},
		{Label: "/", Width: 3, Finger: FingerPinky, EvCode: 53},
		{Label: "Shift", Width: 7, Finger: FingerPinky, EvCode: 54},
		{Label: "↑", Width: 3, Finger: FingerPinky, EvCode: 103},
		{Label: "1", Width: 3, Finger: FingerPinky, EvCode: 79},
		{Label: "2", Width: 3, Finger: FingerPinky, EvCode: 80},
		{Label: "3", Width: 3, Finger: FingerPinky, EvCode: 81},
		{Label: "   ", Width: 3, Finger: FingerPinky, Gap: true, DivLabel: "↵", EvCode: 96},
	},
	// Row 5: Modifiers + arrows + numpad bottom
	{
		{Label: "Ctrl", Width: 6, Finger: FingerPinky, EvCode: 29},
		{Label: "⌘", Width: 3, Finger: FingerRing, EvCode: 125},
		{Label: "Alt", Width: 5, Finger: FingerThumb, EvCode: 56},
		{Label: "Space", Width: 17, Finger: FingerThumb, EvCode: 57},
		{Label: "Alt", Width: 5, Finger: FingerThumb, EvCode: 100},
		{Label: "Fn", Width: 3, Finger: FingerRing, EvCode: 127},
		{Label: "Ctrl", Width: 6, Finger: FingerPinky, EvCode: 97},
		{Label: "←", Width: 3, Finger: FingerPinky, EvCode: 105},
		{Label: "↓", Width: 3, Finger: FingerPinky, EvCode: 108},
		{Label: "→", Width: 3, Finger: FingerPinky, EvCode: 106},
		{Label: "0", Width: 3, Finger: FingerPinky, EvCode: 82},
		{Label: ".", Width: 3, Finger: FingerPinky, EvCode: 83},
		{Label: "   ", Width: 3, Finger: FingerPinky, EvCode: 0},
	},
}

var size100 = [][]Key{
	// Row 0: Esc + F1-F12 + PrSc + ScLk + Pse
	{
		{Label: "⎋", Width: 3, Finger: FingerPinky, EvCode: 1},
		{Label: "   ", Width: 3, Finger: FingerPinky, EvCode: 0},
		{Label: "F1", Width: 3, Finger: FingerPinky, EvCode: 59},
		{Label: "F2", Width: 3, Finger: FingerRing, EvCode: 60},
		{Label: "F3", Width: 3, Finger: FingerMiddle, EvCode: 61},
		{Label: "F4", Width: 3, Finger: FingerIndex, EvCode: 62},
		{Label: "  ", Width: 2, Finger: FingerIndex, EvCode: 0},
		{Label: "F5", Width: 3, Finger: FingerIndex, EvCode: 63},
		{Label: "F6", Width: 3, Finger: FingerIndex, EvCode: 64},
		{Label: "F7", Width: 3, Finger: FingerIndex, EvCode: 65},
		{Label: "F8", Width: 3, Finger: FingerMiddle, EvCode: 66},
		{Label: "  ", Width: 2, Finger: FingerIndex, EvCode: 0},
		{Label: "F9", Width: 3, Finger: FingerRing, EvCode: 67},
		{Label: "F10", Width: 3, Finger: FingerPinky, EvCode: 68},
		{Label: "F11", Width: 3, Finger: FingerPinky, EvCode: 87},
		{Label: "F12", Width: 3, Finger: FingerPinky, EvCode: 88},
		{Label: "  ", Width: 2, Finger: FingerIndex, Gap: true, EvCode: 0},
		{Label: "⎚", Width: 3, Finger: FingerPinky, EvCode: 99},
		{Label: "⚲", Width: 3, Finger: FingerPinky, EvCode: 70},
		{Label: "☼", Width: 3, Finger: FingerPinky, EvCode: 119},
		{Label: " ", Width: 2, Finger: FingerIndex, Gap: true, Rightless: true, EvCode: 0},
		{Label: " ", Width: 3, Finger: FingerIndex, Rightless: true, Leftless: true, EvCode: 0},
		{Label: " ", Width: 3, Finger: FingerIndex, Rightless: true, Leftless: true, EvCode: 0},
		{Label: " ", Width: 3, Finger: FingerIndex, Rightless: true, Leftless: true, EvCode: 0},
		{Label: " ", Width: 3, Finger: FingerIndex, EvCode: 0},
	},
	// Row 1: Number row + Ins + Hme + PgUp + NmLk + / + * + -
	{
		{Label: "`", Width: 3, Finger: FingerPinky, EvCode: 41},
		{Label: "1", Width: 3, Finger: FingerPinky, EvCode: 2},
		{Label: "2", Width: 3, Finger: FingerRing, EvCode: 3},
		{Label: "3", Width: 3, Finger: FingerMiddle, EvCode: 4},
		{Label: "4", Width: 3, Finger: FingerIndex, EvCode: 5},
		{Label: "5", Width: 3, Finger: FingerIndex, EvCode: 6},
		{Label: "6", Width: 3, Finger: FingerIndex, EvCode: 7},
		{Label: "7", Width: 3, Finger: FingerIndex, EvCode: 8},
		{Label: "8", Width: 3, Finger: FingerMiddle, EvCode: 9},
		{Label: "9", Width: 3, Finger: FingerRing, EvCode: 10},
		{Label: "0", Width: 3, Finger: FingerPinky, EvCode: 11},
		{Label: "-", Width: 3, Finger: FingerPinky, EvCode: 12},
		{Label: "=", Width: 3, Finger: FingerPinky, EvCode: 13},
		{Label: "<--", Width: 9, Finger: FingerPinky, EvCode: 14},
		{Label: "  ", Width: 2, Finger: FingerPinky, Gap: true, EvCode: 0},
		{Label: "Ins", Width: 3, Finger: FingerPinky, EvCode: 110},
		{Label: "⌂", Width: 3, Finger: FingerPinky, EvCode: 102},
		{Label: "⇡", Width: 3, Finger: FingerPinky, EvCode: 104},
		{Label: "  ", Width: 2, Finger: FingerPinky, Gap: true, EvCode: 0},
		{Label: "Nlk", Width: 3, Finger: FingerPinky, EvCode: 69},
		{Label: "/", Width: 3, Finger: FingerPinky, EvCode: 98},
		{Label: "*", Width: 3, Finger: FingerPinky, EvCode: 55},
		{Label: "-", Width: 3, Finger: FingerPinky, EvCode: 74},
	},
	// Row 2: Top alpha + Del + End + PgDn + 7 + 8 + 9 + +
	{
		{Label: "Tab ⇄", Width: 7, Finger: FingerPinky, EvCode: 15},
		{Label: "Q", Width: 3, Finger: FingerPinky, EvCode: 16},
		{Label: "W", Width: 3, Finger: FingerRing, EvCode: 17},
		{Label: "E", Width: 3, Finger: FingerMiddle, EvCode: 18},
		{Label: "R", Width: 3, Finger: FingerIndex, EvCode: 19},
		{Label: "T", Width: 3, Finger: FingerIndex, EvCode: 20},
		{Label: "Y", Width: 3, Finger: FingerIndex, EvCode: 21},
		{Label: "U", Width: 3, Finger: FingerIndex, EvCode: 22},
		{Label: "I", Width: 3, Finger: FingerMiddle, EvCode: 23},
		{Label: "O", Width: 3, Finger: FingerRing, EvCode: 24},
		{Label: "P", Width: 3, Finger: FingerPinky, EvCode: 25},
		{Label: "[", Width: 3, Finger: FingerPinky, EvCode: 26},
		{Label: "]", Width: 3, Finger: FingerPinky, EvCode: 27},
		{Label: "\\", Width: 5, Finger: FingerPinky, EvCode: 43},
		{Label: "  ", Width: 2, Finger: FingerPinky, Gap: true, EvCode: 0},
		{Label: "Del", Width: 3, Finger: FingerPinky, EvCode: 111},
		{Label: "⌿", Width: 3, Finger: FingerPinky, EvCode: 107},
		{Label: "⇣", Width: 3, Finger: FingerPinky, EvCode: 109},
		{Label: "  ", Width: 2, Finger: FingerPinky, Gap: true, EvCode: 0},
		{Label: "7", Width: 3, Finger: FingerPinky, EvCode: 71},
		{Label: "8", Width: 3, Finger: FingerPinky, EvCode: 72},
		{Label: "9", Width: 3, Finger: FingerPinky, EvCode: 73},
		{Label: "   ", Width: 3, Finger: FingerPinky, Gap: true, DivLabel: "+", EvCode: 78},
	},
	// Row 3: Home row + gap + 4 + 5 + 6 (blank for +)
	{
		{Label: "Caps", Width: 6, Finger: FingerPinky, EvCode: 58},
		{Label: "A", Width: 3, Finger: FingerPinky, EvCode: 30},
		{Label: "S", Width: 3, Finger: FingerRing, EvCode: 31},
		{Label: "D", Width: 3, Finger: FingerMiddle, EvCode: 32},
		{Label: "F", Width: 3, Finger: FingerIndex, EvCode: 33},
		{Label: "G", Width: 3, Finger: FingerIndex, EvCode: 34},
		{Label: "H", Width: 3, Finger: FingerIndex, EvCode: 35},
		{Label: "J", Width: 3, Finger: FingerIndex, EvCode: 36},
		{Label: "K", Width: 3, Finger: FingerMiddle, EvCode: 37},
		{Label: "L", Width: 3, Finger: FingerRing, EvCode: 38},
		{Label: ";", Width: 3, Finger: FingerPinky, EvCode: 39},
		{Label: "'", Width: 3, Finger: FingerPinky, EvCode: 40},
		{Label: "Enter↵", Width: 10, Finger: FingerPinky, EvCode: 28},
		{Label: " ", Width: 6, Finger: FingerPinky, Gap: true, Rightless: true, Leftless: false, EvCode: 0},
		{Label: " ", Width: 3, Finger: FingerPinky, Gap: false, Rightless: true, Leftless: true, EvCode: 0},
		{Label: " ", Width: 6, Finger: FingerPinky, Gap: true, Rightless: false, Leftless: false, EvCode: 0},
		{Label: "4", Width: 3, Finger: FingerPinky, EvCode: 75},
		{Label: "5", Width: 3, Finger: FingerPinky, EvCode: 76},
		{Label: "6", Width: 3, Finger: FingerPinky, EvCode: 77},
		{Label: "   ", Width: 3, Finger: FingerPinky, EvCode: 0},
	},
	// Row 4: Bottom alpha + ↑ + gap + 1 + 2 + 3 + (Enter blank)
	{
		{Label: "Shift", Width: 11, Finger: FingerPinky, EvCode: 42},
		{Label: "Z", Width: 3, Finger: FingerPinky, EvCode: 44},
		{Label: "X", Width: 3, Finger: FingerRing, EvCode: 45},
		{Label: "C", Width: 3, Finger: FingerMiddle, EvCode: 46},
		{Label: "V", Width: 3, Finger: FingerIndex, EvCode: 47},
		{Label: "B", Width: 3, Finger: FingerIndex, EvCode: 48},
		{Label: "N", Width: 3, Finger: FingerIndex, EvCode: 49},
		{Label: "M", Width: 3, Finger: FingerIndex, EvCode: 50},
		{Label: ",", Width: 3, Finger: FingerMiddle, EvCode: 51},
		{Label: ".", Width: 3, Finger: FingerRing, EvCode: 52},
		{Label: "/", Width: 3, Finger: FingerPinky, EvCode: 53},
		{Label: "Shift", Width: 9, Finger: FingerPinky, EvCode: 54},
		{Label: " ", Width: 2, Finger: FingerPinky, Gap: true, Rightless: true, Leftless: false, EvCode: 0},
		{Label: " ", Width: 3, Finger: FingerPinky, EvCode: 0},
		{Label: "↑", Width: 3, Finger: FingerPinky, EvCode: 103},
		{Label: " ", Width: 3, Finger: FingerPinky, Rightless: true, Leftless: true, EvCode: 0},
		{Label: " ", Width: 2, Finger: FingerPinky, Gap: true, EvCode: 0},
		{Label: "1", Width: 3, Finger: FingerPinky, EvCode: 79},
		{Label: "2", Width: 3, Finger: FingerPinky, EvCode: 80},
		{Label: "3", Width: 3, Finger: FingerPinky, EvCode: 81},
		{Label: " ", Width: 3, Finger: FingerPinky, Gap: true, DivLabel: "↵", EvCode: 96},
	},
	// Row 5: Modifiers + arrows + gap + 0 + . + (Enter blank)
	{
		{Label: "Ctrl", Width: 6, Finger: FingerPinky, EvCode: 29},
		{Label: "⌘", Width: 3, Finger: FingerRing, EvCode: 125},
		{Label: "Alt", Width: 5, Finger: FingerThumb, EvCode: 56},
		{Label: "Space", Width: 23, Finger: FingerThumb, EvCode: 57},
		{Label: "Alt", Width: 5, Finger: FingerThumb, EvCode: 100},
		{Label: "⌘", Width: 3, Finger: FingerRing, EvCode: 126},
		{Label: "Fn", Width: 3, Finger: FingerRing, EvCode: 127},
		{Label: "Ctrl", Width: 6, Finger: FingerPinky, EvCode: 97},
		{Label: "  ", Width: 2, Finger: FingerPinky, EvCode: 0},
		{Label: "←", Width: 3, Finger: FingerPinky, EvCode: 105},
		{Label: "↓", Width: 3, Finger: FingerPinky, EvCode: 108},
		{Label: "→", Width: 3, Finger: FingerPinky, EvCode: 106},
		{Label: "  ", Width: 2, Finger: FingerPinky, Gap: true, EvCode: 0},
		{Label: "0", Width: 7, Finger: FingerPinky, EvCode: 82},
		{Label: ".", Width: 3, Finger: FingerPinky, EvCode: 83},
		{Label: "   ", Width: 3, Finger: FingerPinky, EvCode: 0},
	},
}
